name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.yursyla }}" > "$HOME/.ssh/yursyla"
      - run: chmod 600 "$HOME/.ssh/yursyla"
      # Deploy
      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/yursyla -o StrictHostKeyChecking=no" --archive --compress --delete . /home/yursyla/yursyla.com.ua/www/
      